"""This module allows binding events to __setattr__, but only taking effect after __init__."""

import typing as _typing
import warnings as _warnings


ClazzType = _typing.TypeVar("ClazzType", bound=type)

def later_on_setattr(func: _typing.Callable) -> _typing.Callable[[ClazzType], ClazzType]:
    """To bind any function to `__setattr__`. 
    
    on_setattr class decorator factory.

    :param func: Callable to bind
    """
    def decorator(clazz: type):
        """A class decorator generated by on_setattr().

        :param clazz: The class to decorate
        """
        original_init_func = clazz.__init__
        original_setattr_func = clazz.__setattr__
        def new_setattr(self, name: str, value: _typing.Any) -> None:
            """The overwritten `__setattr__` function.

            Params same as an ordinary `__setattr__`, with an additional to reveive old value.
            """
            old = getattr(self, name) if hasattr(self, name) else None
            original_setattr_func(self, name, value) # type: ignore
            if hasattr(self, "_setattr_detection_initialized"):
                if self._setattr_detection_initialized:
                    func(self, name, value, old)
            # print("Run hijackted setattr with bound func")
        def new_init(self, *args, **kwargs):
            """The overwritten __init__ function."""
            original_init_func(self, *args, **kwargs)
            self._setattr_detection_initialized = True
        clazz.__init__ = new_init
        clazz.__setattr__ = new_setattr # type: ignore
        if _typing.TYPE_CHECKING:
            clazz = _typing.cast(ClazzType, clazz)
        return clazz
    return decorator

def apply_on_setattr(clazz: ClazzType) -> ClazzType:
    """To execute `clazz._on_setattr()` each time on `__setattr__` after `__init__`.

    apple_on_setattr is a class decorator

    The class to be decorated must have a `_on_setattr` function to bind, which should take exactly 
    same args as `__setattr__`.
    """
    if not hasattr(clazz, "_on_setattr"):
        _warnings.warn("Nothing given to apply_on_setattr to bind.")
        return clazz
    on_setattr = clazz._on_setattr
    return later_on_setattr(on_setattr)(clazz)